### ISSUE TITLE
How to use plugins?

### ISSUE THREAD

**Issue by schnapi** [fr3ts0n/AndrOBD-Plugin#1]
I am quite new in android.
Do I need to install each plugin? I can see MqttPublisher in PluginHost only when I installDebug MqttPublisher first. Also I have to run MqttPublisher before PluginHost if I want to identify plugin.

If I understand right each plugin is installed as seperate app.

Thanks!

**Comment by fr3ts0n** [comment]
Hi @schnapi,

Yes, each plugin has to be installed as a separate apk package / app.
- It may be installed after the host application (AndrOBD) though

After Installation the plugin should be started once for initial configuration.
- Furhter on it will be started automatically with the start of AndrOBD

Within the AndrOBD plugin manager you can enable/disable the communication to the plugin, to allow each installed plugin to be disabled.

From AndrOBD plugin manager you can:
* Scan for all installed plugins
* Trigger each plugin's configuration dialogue
* Trigger each plugin's action (i.e. MQTT publish) manually 

For more details please see: [Plugin design doc](https://github.com/fr3ts0n/AndrOBD/wiki/Design:---AndrOBD-extension-plugin-framework)
