### ISSUE TITLE
In new packages, how do you link to com.fr3ts0n.androbd.plugin.Plugin

### ISSUE THREAD

**Issue by jgpATs2w** [fr3ts0n/AndrOBD-Plugin#3]
You need to resolve the dependencies to make the following code to work:
```
import com.fr3ts0n.androbd.plugin.Plugin;
import com.fr3ts0n.androbd.plugin.PluginInfo;
public class HttpPlugin
    extends Plugin{
...
```
Is there a jar file with the library, do I need to compile it from the project, or include the Java file in my package?

**Comment by fr3ts0n** [comment]
The package com.fr3ts0n.androbd.plugin is contained in the "plugin" directory.
This comes from repo "AndrOBD-libplugin" which is a shared submodule between AndrOBD-Plugin and AndrOBD repositories
