### ISSUE TITLE
MQTT encryption support?

### ISSUE THREAD

**Issue by nwmcsween** [fr3ts0n/AndrOBD-Plugin#4]
As per title could the MQTT plugin support TLS?

**Comment by fr3ts0n** [comment]
I am afraid, currently no.
However, the used library (paho) does support ssl/tls prot, but currently the plugin just requests using tcp:// uri scheme.

I'm not sure if the library automatically changes to ssl/tls if you attempt to connect to the broker address on port 8883. That would be worth a try. 
Unfortunately I currently do not have a broker set up with TLS, so I cannot verify that here.

Do you have the chance to give that a try?
If that does not work I would need to extend the configuration to allow selection of the uri scheme (tcp, ssl)

Thx

**Comment by fr3ts0n** [comment]
Plugin V1.0.1 will allow selection of ssl:// protocol as well. 
It will be available on FDROID soon :+1:
