### ISSUE TITLE
Three AndrOBD-Plugin title should be different

### ISSUE THREAD

**Issue by 532910** [fr3ts0n/AndrOBD-Plugin#8]
https://gitlab.com/fdroid/fdroiddata/issues/1825

**Comment by IzzySoft** [comment]
TL;DR: `fastlane/metadata/android/en-US/title.txt` is identical for all 3 plugins. It should be specific, else in search they all turn up with the same "name".

**Comment by fr3ts0n** [comment]
Hi @IzzySoft @532910 ,

Thanks for the report. I'll answer on the fdroid issue ...

**Comment by IzzySoft** [comment]
Thanks! Answered there. My bad: I totally missed that all 3 plugins share the same repo, so AFAIK it's not possible to fix that with Fastlane and you'd probably need to switch to Triple-T. Details over there.

**Comment by 532910** [comment]
Any update?

**Comment by IzzySoft** [comment]
If @fr3ts0n doesn't want to switch to Triple-T (which I completely understand), there are two options (insider details :wink:):

* just put the `title.txt` details into Triple-T. In the index process at F-Droid, Triple-T collection runs after Fastlane, and thus would then overwrite `title.txt` taken from Fastlane.
* not strictly alternative (the above could be done now and later rolled back): Wait a little longer. Currently there's [a discussion at fdroidserver](https://gitlab.com/fdroid/fdroidserver/-/issues/829) to rework how F-Droid deals with Fastlane. Short abstract for the case here: at some point, in addition to `<repoRoot>/fastlane`, fdroidserver will also support something like `<repoRoot>/<project>/<flavor>/fastlane`, which is looked for first (the global one then is only looked for if the specific one was not found). That would allow sticking for the much easier Fastlane structures while still supporting flavor-specific things.

**Comment by fr3ts0n** [comment]
@IzzySoft - Thank you for fixing this behaviour on F-Droid :+1:

**Comment by IzzySoft** [comment]
Uh? Credits whom credits are due – but I didn't fix that. I might have nudged a little here or there… But the important thing is: glad if it's fixed!
