### ISSUE TITLE
Option to use Websockets Mqtt Plugin

### ISSUE THREAD

**Issue by diabl0w** [fr3ts0n/AndrOBD-Plugin#9]
Hello, thanks for this great app!

I am not super knowledgable in programming or anything, I am just a tinkerer. But from what I understand, if you want to use mqtt over the internet (publishing back to home while driving), then most people use mqtt through websockets, and that is what I use. I know paho supports websockets so I would think it might be easy to implement but I guess I wouldnt really know for sure.

**Comment by ryansun96** [comment]
See my pull request above

**Comment by fr3ts0n** [comment]
Released with V1.1.0

**Comment by DeadSamurai8** [comment]
> Hello, thanks for this great app!
> 
> I am not super knowledgable in programming or anything, I am just a tinkerer. But from what I understand, if you want to use mqtt over the internet (publishing back to home while driving), then most people use mqtt through websockets, and that is what I use. I know paho supports websockets so I would think it might be easy to implement but I guess I wouldnt really know for sure.

**Comment by fr3ts0n** [comment]
WebSocket is supported in the MqttPublisher plugin since V1.1.0.
* You can select ws:// or wss:// transport protocol in Settings -> MQTT protocol
